### ISSUE TITLE
Cannot set Mixer to Software after using the driver

### ISSUE THREAD

**Issue by Burk015** [MKSounds/ADAU1701-I2S-Audio-Driver-for-Raspberry-Pi#2]
Hi MK,
use Raspi 2 and volumio. After succesful installation of your driver wanted change the mixer to software but end in an update loop where volumio is no longer accessible via website only via ssh.
Tried also the fix of luckynrslevin  fix softvolume bugs #1288 but still the same.
Any idea?

**Comment by MKSounds** [comment]
Hi,
that is just a really basic i2s audio driver without any controls or mixers. If you need a mixer, you must implement that on your own.
